-- Bases applicatives dans l'unique instance PostgreSQL.
CREATE DATABASE n8n      OWNER CURRENT_USER;
CREATE DATABASE listmonk OWNER CURRENT_USER;
CREATE DATABASE twenty   OWNER CURRENT_USER;
CREATE DATABASE kanboard OWNER CURRENT_USER;
